from pathlib import Path

p=Path('src/aster.c')
s=p.read_text()
old="""static int rule_matches(const AsterDocument*d,const AsterCssRule*r,const AsterNode*n){if(r->tag!=CSS_ANY_TAG&&r->tag!=n->tag)return 0;switch(r->selector_kind){case CSS_SELECTOR_ANY:case CSS_SELECTOR_TAG:return 1;case CSS_SELECTOR_CLASS:case CSS_SELECTOR_TAG_CLASS:return class_has(d,n,r->selector_off,r->selector_len);case CSS_SELECTOR_ID:case CSS_SELECTOR_TAG_ID:return n->id_len&&text_eq_range(d,n->id_off,n->id_len,d->text+r->selector_off,r->selector_len);default:return 0;}}\nstatic uint8_t rule_specificity(const AsterCssRule*r){switch(r->selector_kind){case CSS_SELECTOR_ID:return 100;case CSS_SELECTOR_TAG_ID:return 101;case CSS_SELECTOR_CLASS:return 10;case CSS_SELECTOR_TAG_CLASS:return 11;case CSS_SELECTOR_TAG:return 1;default:return 0;}}\nstatic void apply_rule_for(const AsterDocument*d,int node,ParsedStyle*st){const AsterNode*n=&d->nodes[node];uint8_t color_spec=0,scale_spec=0;int color_order=-1,scale_order=-1;for(uint8_t i=0;i<d->css_count;i++){const AsterCssRule*r=&d->css[i];if(!rule_matches(d,r,n))continue;uint8_t spec=rule_specificity(r);"""
new="""static int class_has_all(const AsterDocument*d,const AsterNode*n,uint16_t off,uint16_t len){if(!len||(size_t)off+len>ASTER_TEXT_CAP)return 0;uint16_t p=0;while(p<len){uint16_t a=p;while(p<len&&d->text[off+p]!='.')p++;uint16_t count=(uint16_t)(p-a);if(!count||!class_has(d,n,(uint16_t)(off+a),count))return 0;if(p<len)p++;}return 1;}\nstatic int rule_matches(const AsterDocument*d,const AsterCssRule*r,const AsterNode*n){if(r->tag!=CSS_ANY_TAG&&r->tag!=n->tag)return 0;switch(r->selector_kind){case CSS_SELECTOR_ANY:case CSS_SELECTOR_TAG:return 1;case CSS_SELECTOR_CLASS:case CSS_SELECTOR_TAG_CLASS:return class_has_all(d,n,r->selector_off,r->selector_len);case CSS_SELECTOR_ID:case CSS_SELECTOR_TAG_ID:return n->id_len&&text_eq_range(d,n->id_off,n->id_len,d->text+r->selector_off,r->selector_len);default:return 0;}}\nstatic uint8_t rule_specificity(const AsterDocument*d,const AsterCssRule*r){switch(r->selector_kind){case CSS_SELECTOR_ID:return 100;case CSS_SELECTOR_TAG_ID:return 101;case CSS_SELECTOR_CLASS:case CSS_SELECTOR_TAG_CLASS:{unsigned classes=1;for(uint16_t i=0;i<r->selector_len;i++)if(d->text[r->selector_off+i]=='.')classes++;unsigned spec=classes*10u+(r->selector_kind==CSS_SELECTOR_TAG_CLASS?1u:0u);return (uint8_t)(spec>250u?250u:spec);}case CSS_SELECTOR_TAG:return 1;default:return 0;}}\nstatic void apply_rule_for(const AsterDocument*d,int node,ParsedStyle*st){const AsterNode*n=&d->nodes[node];uint8_t color_spec=0,scale_spec=0;int color_order=-1,scale_order=-1;for(uint8_t i=0;i<d->css_count;i++){const AsterCssRule*r=&d->css[i];if(!rule_matches(d,r,n))continue;uint8_t spec=rule_specificity(d,r);"""
if old not in s: raise SystemExit('matcher anchor not found')
p.write_text(s.replace(old,new,1))

t=Path('tests/parser_smoke.c')
s=t.read_text()
s=s.replace(".accent,#other{text-decoration:underline}#gone{display:none}",".accent,#other{text-decoration:underline}.notice.accent{color:#0a0b0c}p.notice.accent{font-size:24px}#gone{display:none}")
s=s.replace("<p id='other'>Other</p>","<p id='other'>Other</p><p class='notice accent'>Compound</p>")
s=s.replace("if(d.css_count<7)return 2;","if(d.css_count<9)return 2;")
s=s.replace("int saw_hero=0,saw_other=0,saw_image=0;","int saw_hero=0,saw_other=0,saw_compound=0,saw_image=0;")
s=s.replace("if((p->flags&ASTER_PAINT_UNDERLINE)&&p->color==0x123456)saw_other=1;","if((p->flags&ASTER_PAINT_UNDERLINE)&&p->color==0x123456)saw_other=1;\n        if((p->flags&ASTER_PAINT_BOLD)&&(p->flags&ASTER_PAINT_UNDERLINE)&&p->color==0x0A0B0C&&p->scale==2)saw_compound=1;")
s=s.replace("if(!saw_hero||!saw_other||!saw_image)return 3;","if(!saw_hero||!saw_other||!saw_compound||!saw_image)return 3;")
if 'saw_compound' not in s: raise SystemExit('smoke patch failed')
t.write_text(s)
